### ISSUE TITLE
Wrong results

### ISSUE THREAD

**Issue by luczeng** [jfemiani/facade-segmentation#4]
Hello,

I ran your code on my machines and everything worked well, however the segmentation results only output a noisy map. This is the default image provided in the repo:

![segnet-i12-facade](https://user-images.githubusercontent.com/28003333/55964651-619b2f80-5c75-11e9-8193-e528ae293b90.jpg)

I use the following environment:
GPU: NVIDIA GTX 1080 (8Gb)
Nvidia-docker 2
CUDA 8.0 image that you created (segnet-facade:cuda8-cudnn3). (For some reason I don't understand the image with CUDA 7.5 didn't work on my machine)

I only get a few warning during inference:
`libdc1394 error: Failed to initialize libdc1394`  
` Only one label was provided to `remove_small_objects`. Did you mean to use a boolean array?`

Any idea why I get these results?

Thanks

**Comment by twak** [comment]
I've seen similar issues. Does this [docker container](https://cloud.docker.com/u/twak/repository/docker/twak/segnet-facade) work better?

**Comment by luczeng** [comment]
Yes it works, but i guess you refer to this [link](https://hub.docker.com/r/twak/segnet-facade).
Thanks a bunch!

Any idea of the reason for this bug? I saw in John Femiani's video that his container is supposed to work for 1070 or 1080 GPUs.

**Comment by twak** [comment]
It was something to do with CUDA drivers on my Ubuntu - involved patching in some a particular version from the nvidia website. I'm not sure if john has pulled my patch\built it\rolled over to the latest version!
